### ISSUE TITLE
Remove navigator.appVersion (deprecated) from cwd.js

### ISSUE THREAD

**Issue by inaydich** [CU-CommunityApps/cwd_base_wp#5]
navigator.appVersion and navigator.appName are deprecated now. We need to either replace them with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
I rather suggest to drop the IE support, even MS doesn't support anymore IE.

**Comment by dc774** [comment]
This is a "core" file from the CSS Framework, so this should it should be raised there and addressed to Tone.
